# {{- if .Values.pvc.enabled }}
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: vikare-data
# spec:
#   accessModes: {{ .Values.pvc.accessModes }}
#   resources:
#     requests:
#       storage: {{ .Values.pvc.size }}
#   {{- if .Values.pvc.storageClassName }}
#   storageClassName: {{ .Values.pvc.storageClassName }}
#   {{- end }}
# {{- end }}
